export enum Code {
  OK = "OK",
  Canceled = "CANCELLED",
  Unknown = "UNKNOWN",
  InvalidArgument = "INVALID_ARGUMENT",
  DeadlineExceeded = "DEADLINE_EXCEEDED",
  NotFound = "NOT_FOUND",
  AlreadyExists = "ALREADY_EXISTS",
  PermissionDenied = "PERMISSION_DENIED",
  Unauthenticated = "UNAUTHENTICATED",
  ResourceExhausted = "RESOURCE_EXHAUSTED",
  FailedPrecondition = "FAILED_PRECONDITION",
  Aborted = "ABORTED",
  OutOfRange = "OUT_OF_RANGE",
  Unimplemented = "UNIMPLEMENTED",
  Internal = "INTERNAL",
  Unavailable = "UNAVAILABLE",
  DataLoss = "DATA_LOSS",
}
