name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  CI: "true"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  deno:
    name: Deno
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check
        run: deno check src/mod.ts
